apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend_service.app }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.backend_service.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend_service.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend_service.app }}
        project: {{ .Values.project }}
    spec:
      containers:
      - name: {{ .Values.backend_service.app }}
        image: {{ .Values.backend_service.deployment.image }}
        imagePullPolicy: {{ .Values.backend_service.deployment.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.backend_service.deployment.cpuLimit }}
            memory: {{ .Values.backend_service.deployment.memoryLimit }}          
          requests:
            cpu: 1m
            memory: 1Mi
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{ .Values.backend_service.app }}
        env:
        - name: PSQL_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend_service.app }}
              key: PSQL_PASS
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend_service.app }}
              key: MAIL_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend_service.app }}
              key: REDIS_PASSWORD
        - name: ACCESS_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend_service.app }}
              key: ACCESS_REFRESH_TOKEN
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend_service.app }}
              key: ENCRYPTION_KEY
        volumeMounts:
          {{- toYaml .Values.backend_service.volumeMounts | default "" | nindent 12 }}
      volumes:
        {{- toYaml .Values.backend_service.volumes | default "" | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end}}