apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend_service.app }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.backend_service.app }}
    project: {{ .Values.project }}
type: Opaque
data:
  PSQL_PASS: {{ .Values.backend_service.secret.psqlPass }}
  MAIL_PASSWORD: {{ .Values.backend_service.secret.mailPassword }}
  REDIS_PASSWORD: {{ .Values.backend_service.secret.redisPassword }}
  ACCESS_REFRESH_TOKEN: {{ .Values.backend_service.secret.accessRefreshToken }}
  ENCRYPTION_KEY: {{ .Values.backend_service.secret.encryptionKey }}