apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.redis.app }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.redis.app }}
    project: {{ .Values.project }}
data:
  redis.conf: |
    masterauth dap
    requirepass dap2023
    dir "/data"
