apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.app }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.redis.app }}
    project: {{ .Values.project }}
spec:
  selector:
    app: {{ .Values.redis.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: 6379