apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.app }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.redis.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.app }}
        project: {{ .Values.project }}
    spec:
      containers:
      - name: {{ .Values.redis.app }}
        image: {{ .Values.redis.statefulset.image }}
        imagePullPolicy: {{ .Values.redis.statefulset.imagePullPolicy }}
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        env:
        - name: MASTER
          value: "true"
        resources:
          limits:
            cpu: {{ .Values.redis.statefulset.cpuLimit }}
            memory: {{ .Values.redis.statefulset.memoryLimit }}          
          requests:
            cpu: 1m
            memory: 1Mi
        volumeMounts:
        - name: {{ .Values.redis.app }} 
          mountPath: /data
          subPath: {{ .Values.redis.app }}
        - name: {{ .Values.redis.app }}-config
          mountPath: /etc/redis/
      volumes:
      - name: {{ .Values.redis.app }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc }}
      - name: {{ .Values.redis.app }}-config
        configMap:
          name: {{ .Values.redis.app }}
