package groupauthorizationrules

const (
	RULE_GROUP_APP_INSTANCES                 string = "app_instances"
	RULE_GROUP_GROUP_RULE_AUTHORIZATION      string = "group_rule_authorization"
	RULE_GROUP_IAM_GROUP_AUTHORIZATION       string = "iam_group_authorization"
	RULE_GROUP_DIRECTORY_GROUPS              string = "directory_groups"
	RULE_GROUP_DIRECTORY_GROUPS_TYPES        string = "directory_groups_types"
	RULE_GROUP_DIRECTORY                     string = "directory"
	RULE_GROUP_IAM_CREDENTIALS               string = "iam_credentials"
	RULE_GROUP_METADATA_MODELS               string = "metadata_models"
	RULE_GROUP_METADATA_MODELS_DEFAULTS      string = "metadata_models_defaults"
	RULE_GROUP_STORAGE_DRIVES                string = "storage_drives"
	RULE_GROUP_STORAGE_FILES                 string = "storage_files"
	RULE_GROUP_INVENTORY                     string = "inventory"
	RULE_GROUP_INVENTORY_STOCK               string = "inventory_stock"
	RULE_GROUP_INVENTORY_STOCK_GROUP         string = "inventory_stock_group"
	RULE_GROUP_INVENTORY_STOCK_KEEPING_UNITS string = "inventory_stock_keeping_units"
	RULE_GROUP_CHAT_CHANNELS                 string = "chat_channels"
	RULE_GROUP_CHAT_MESSAGES                 string = "chat_messages"
	RULE_GROUP_CHAT_BOTS                     string = "chat_bots"

	RULE_CREATE                 string = "create"
	RULE_ASSIGN_CREATE          string = "assign_create"
	RULE_CREATE_OTHERS          string = "create_others"
	RULE_ASSIGN_CREATE_OTHERS   string = "assign_create_others"
	RULE_RETRIEVE_SELF          string = "retrieve_self"
	RULE_ASSIGN_RETRIEVE_SELF   string = "assign_retrieve_self"
	RULE_RETRIEVE               string = "retrieve"
	RULE_ASSIGN_RETRIEVE        string = "assign_retrieve"
	RULE_RETRIEVE_OTHERS        string = "retrieve_others"
	RULE_ASSIGN_RETRIEVE_OTHERS string = "assign_retrieve_others"
	RULE_UPDATE                 string = "update"
	RULE_ASSIGN_UPDATES         string = "assign_update"
	RULE_UPDATE_SELF            string = "update_self"
	RULE_ASSIGN_UPDATE_SELF     string = "assign_update_self"
	RULE_UPDATE_OTHERS          string = "update_others"
	RULE_ASSIGN_UPDATE_OTHERS   string = "assign_update_others"
	RULE_DELETE                 string = "delete"
	RULE_ASSIGN_DELETE          string = "assign_delete"
	RULE_DELETE_SELF            string = "delete_self"
	RULE_ASSIGN_DELETE_SELF     string = "assign_delete_self"
	RULE_DELETE_OTHERS          string = "delete_others"
	RULE_ASSIGN_DELETE_OTHERS   string = "assign_delete_others"
	RULE_ASSIGN_ALL             string = "assign_all"
)
