name: keycloak

services:
  keycloak:
    image: ${KEYCLOAK_CONTAINER_IMAGE}
    container_name: keycloak
    ports:
    - "${KC_HTTP_PORT:-8080}:${KC_HTTP_PORT:-8080}"
    - "${KC_HTTP_MANAGEMENT_PORT:-9000}:${KC_HTTP_MANAGEMENT_PORT:-9000}"
    restart: always
    command: ${KEYCLOACK_START_COMMAND:-start --optimized --hostname=localhost}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KC_HTTP_PORT:-8080}
      KC_HTTP_MANAGEMENT_PORT: ${KC_HTTP_MANAGEMENT_PORT:-9000}
      KC_PROXY: edge
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "${KC_CPU_LIMIT:-2}"
          memory: ${KC_MEMORY_LIMIT:-4gb}

networks:
  default:
    external:
      name: ${EXTERNAL_NETWORK_NAME}
