apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend_service.app }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.backend_service.app }}
    project: {{ .Values.project }}
spec:
  selector:
    app: {{ .Values.backend_service.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend_service.service.port }}
      targetPort: 3000