apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend_web.app }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ .Values.frontend_web.app }}
    project: {{ .Values.project }}
data:
    ORIGN: {{ .Values.frontend_web.config.orign }}
    BODY_SIZE_LIMIT: "{{ .Values.frontend_web.config.bodySizeLimit }}"