apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend_web.app }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.frontend_web.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend_web.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend_web.app }}
        project: {{ .Values.project }}
    spec:
      containers:
      - name: {{ .Values.frontend_web.app }}
        image: {{ .Values.frontend_web.deployment.image }}
        imagePullPolicy: {{ .Values.frontend_web.deployment.imagePullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.frontend_web.deployment.cpuLimit }}
            memory: {{ .Values.frontend_web.deployment.memoryLimit }}
          requests:
            cpu: 1m
            memory: 1Mi
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: {{ .Values.frontend_web.app }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end}}